---
- name: Enable cgroup via GRUB commandline if not already enabled for standard Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"'
  notify: update-grub

- name: Install linux-modules-extra package if necessary
  ansible.builtin.apt:
    name: linux-modules-extra-$(uname -r)
    state: present
  when: ansible_distribution_version is version('24.04', '<')
